[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "b3ac9a674d35c322d3739673265d95e54938f516"
os = "macos"

    [[Ogg.download]]
    sha256 = "beba0e8a03468344cfa71655aa2a250eee838e3610ba7fca6458068afdd4b691"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.aarch64-apple-darwin.tar.gz"
[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "735286b81f1df85c567bbf4997522bac4e0e7130"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "1b0a619023a47e79c9052bf4a8d73b57ee1dd351143f644b8f6a20618f186bd0"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.aarch64-linux-gnu.tar.gz"
[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "92089eef9ec760dc80100b3ca7c979ddad5c94f4"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "811a65999b45e7a28e3560711c38f25a5adfb4788887cd99bcd1cfa0ac80d0e0"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.aarch64-linux-musl.tar.gz"
[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "ef3473bb98f005d1d604fc649a2b96e9d4ef8832"
os = "freebsd"

    [[Ogg.download]]
    sha256 = "b49e77c90f027bbea82d1e7cb1a39d5c5bfe1dfa9ea86e62124a82fda94518ca"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.aarch64-unknown-freebsd.tar.gz"
[[Ogg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eb52023d43663930547fb2dbdb4bea0fc4a83f30"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "c1fe41700077e06a6a07644c3e0dbe8db6390fd88a7ee814be3f6fe87ec36faa"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.armv6l-linux-gnueabihf.tar.gz"
[[Ogg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f3ebb16e76740de0352a43099fd8eda8a6f21046"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "1eb3042dc16667b776d17e8028dfec5bb32ae8607d19fefcabfe1825a03a3204"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.armv6l-linux-musleabihf.tar.gz"
[[Ogg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48162665456a4b3cc7e24c93f22a6bd186466e16"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "f59e944e360860d173e58bb47e2ce37fa58210fa764055aa34490cd39e18778c"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.armv7l-linux-gnueabihf.tar.gz"
[[Ogg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2bac233e645205fdd907404461a69d12490a9e4"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "f1ee31d32568f3100a4e32d5b13898e2548d71544e8753907142e533f45b841c"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.armv7l-linux-musleabihf.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "4dce096082eb53995bdc776a717f4ddd33c462e2"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "b24aa0420946ac95513653a64b48efe17e38b7e00fac61a064e95ae6c53b12b4"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.i686-linux-gnu.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "52a91c3cdbb233a601bbc4c7a67e27afa00b611c"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "eaf2e55dc9af746a840d272a532516d5e0dd1c8a8c9dddef65847c8fe9ceba9f"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.i686-linux-musl.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "d5365c91bfc80484820231badb61ffb43f63db99"
os = "windows"

    [[Ogg.download]]
    sha256 = "b9fc07f995ec281b1ef10392d8d4bd7a18eb80504079bf2386d6373d2f3003d2"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.i686-w64-mingw32.tar.gz"
[[Ogg]]
arch = "powerpc64le"
git-tree-sha1 = "9091fa5c7f8e6ecff3b667cc9d8e06c64c648b06"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "cb58da6222236a5209c953760e38d90f244f854f0ebd6d47b71f76031eb2aa7e"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.powerpc64le-linux-gnu.tar.gz"
[[Ogg]]
arch = "riscv64"
git-tree-sha1 = "fa51cd103751925cfaa9f20038b28da2addb3ab4"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "e735dea8d571e291d241629b70a320a9669e18aad3c80f074a4a49669bec0fe1"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.riscv64-linux-gnu.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "bdb77b78287cb043d660d157f56af0d9ce46cbb7"
os = "macos"

    [[Ogg.download]]
    sha256 = "c59e519901498dd869fb04909e4abbde28a943434105363d6dbe37dcbc79b368"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.x86_64-apple-darwin.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "8e4faedde4bd75566bc8da1fccecb257eb6af6f2"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "420b3a0d1c3c7750ee6876c4c4618fe2cb82d080087f145ea87b75f1d2a223ed"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.x86_64-linux-gnu.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "1961b904f267404f6821ce77ff87e154161eee81"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "a4d0fd5b7ca1cf21cf8066d75d7c528334c1869d62499b311edabb973c2ce0ee"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.x86_64-linux-musl.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "6e62cb63af0cdeb0707302b5e03b521bbd07406f"
os = "freebsd"

    [[Ogg.download]]
    sha256 = "7b2989d54620b655944a4bea1c4838c4795b8a5826eeff699e7a3359881b5551"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.x86_64-unknown-freebsd.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "8258f1ad1bf2f9853eb157e9d4b755f0e427a0ea"
os = "windows"

    [[Ogg.download]]
    sha256 = "1cc5ab128019f0ef0b2974ef46816c69e1423b4b1fa0992d4c2ece3ff44fe06c"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.6+0/Ogg.v1.3.6.x86_64-w64-mingw32.tar.gz"
